komax_site/api/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.routers import DefaultRouter
from .viewsets import KomaxViewSet, KappaViewSet, HarnessViewSet, LabourisnessViewSet, KomaxTerminalsViewSet, \
    KomaxStatusViewSet, HarnessChartViewSet, KomaxSealViewSet, WorkerViewSet, KomaxTaskViewSet

app_name = 'api'

router = DefaultRouter()
router.register('komaxes', KomaxViewSet)
router.register('kappas', KappaViewSet)
router.register('harnesses', HarnessViewSet)
router.register('laboriousness', LabourisnessViewSet)
router.register('komax_terminals', KomaxTerminalsViewSet)
router.register('komax_status', KomaxStatusViewSet)
router.register('harness_chart', HarnessChartViewSet)
router.register('komax_seals', KomaxSealViewSet)
router.register('workers', WorkerViewSet)
router.register('komax_tasks', KomaxTaskViewSet, basename='komax-tasks')


urlpatterns = [
    path('index/', views.index, name='index'),
    path('v1/login/', ObtainAuthToken.as_view(), name='get_token'),
    path('v1/logout/', views.Logout.as_view(), name='logout'),
    path('v1/<str:task_name>/stop', views.KomaxTaskStop.as_view(), name='stop_task'),
    path('v1/<str:task_name>/stop/<str:komax>/', views.KomaxTaskStopOnKomax.as_view(), name='stop_task_on_komax'),
    path('v1/load_komax_task/', views.LoadTaskView.as_view(), name='load-komax-task'),
    path('v1/send_komax_task/', views.SendTaskView.as_view(), name='send-komax-task'),
    path('v1/worker_account/', views.WorkerAccountView.as_view(), name='worker-account'),
    path('v1/komax_task_status/', views.TaskStatusView.as_view(), name='komax-task-status'),
    path('v1/groups/', views.UserGroupView.as_view(), name='user-groups'),
    path('v1/<str:task_name>/get_task/', views.get_general_task_view, name='get_task'),
    path('v1/<str:task_name>/get_task_komax/<str:komax>/',
         views.get_personal_task_view_komax, name='get_spec_task'),
    path('v1/<str:task_name>/get_task_kappa/<str:kappa>/',
         views.get_personal_task_view_kappa, name='get_spec_task_kappa'),
    path('v1/<str:task_name>/get_ticket_komax/<str:komax>/',
         views.get_komax_ticket_view, name='get_ticket_view'),
    path('v1/<str:task_name>/get_ticket_kappa/<str:kappa>/',
         views.get_kappa_ticket_view, name='get_kappa_ticket_view'),
    # path('v1/xlsx_task/', views.XlsxTaskView.as_view(), name='xlsx-task'),
    path('v1/', include(router.urls)),
]

komax_site/description/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

app_name = 'description'
urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='description/description.html'), name='description'),
]

komax_site/komax_app/urls.py
from django.urls import path
from . import views

app_name = 'komax_app'

urlpatterns = [
    # main
    path('', views.MainPageKomaxAppView.as_view(), name='komax_app_view'),

    # komax api
    path('api/v1/komax/', views.KomaxClientView.as_view(), name='komax_client'),

    # tasks
    path('tasks/', views.TasksView.as_view(), name='tasks_view'),
    path('account/', views.WorkerAccountView.as_view(), name='user_account'),
    path('tasks/setup/', views.KomaxTaskSetupView.as_view(), name='task_setup'),
    path('tasks/<str:task_name>/', views.KomaxTaskView.as_view(), name='task_view'),
    path('tasks/<str:task_name>/delete/', views.delete_task, name='delete_task'),
    path('tasks/<str:task_name>/stop', views.stop_komax_task, name='stop_task'),
    path('tasks/<str:task_name>/stop/<str:komax>/', views.stop_task_on_komax, name='stop_task_on_komax'),
    path('tasks/<str:task_name>/get_task/', views.get_general_task_view, name='get_task'),
    path('tasks/<str:task_name>/get_task_komax/<str:komax>/',
            views.get_personal_task_view_komax, name='get_spec_task'),
    path('tasks/<str:task_name>/get_task_kappa/<str:kappa>/',
            views.get_personal_task_view_kappa, name='get_spec_task_kappa'),
    path('tasks/<str:task_name>/get_ticket_komax/<str:komax>/',
            views.get_komax_ticket_view, name='get_ticket_view'),
    path('tasks/<str:task_name>/get_ticket_kappa/<str:kappa>/',
         views.get_kappa_ticket_view, name='get_kappa_ticket_view'),
    path('tasks/<str:task_name>/send_task/', views.send_task_to_worker,
                name='send_komax_task'),
    path('tasks/<task_name>/load_task/', views.load_task_to_komax, name='load_komax_task'),

    # harnesses
    path('harnesses/', views.HarnessesListView.as_view(), name='harnesses'),
    path('harnesses/<str:harness_number>', views.harness_chart_view, name='harness_chart'),
    path('harnesses/<str:harness_number>/delete/', views.harness_delete, name='delete_harness'),
    path('harnesses/<str:harness_number>/download/', views.get_harness_chart_view, name='download_harness'),

    # komaxes
    path('komaxes/', views.EquipmentListView.as_view(), name='komaxes'),

    # laboriousness
    path('laboriousness/edit/<str:action>/delete/', views.LaboriousnessDeleteView.as_view(), name='laboriousness-delete'),
    path('laboriousness/create/', views.LaboriousnessCreateView.as_view(), name='laboriousness-create'),
    path('laboriousness/edit/<str:action>', views.LaboriousnessEditView.as_view(), name='laboriousness-edit'),
    path('laboriousness/', views.LaboriousnessListView.as_view(), name='laboriousness'),

    # others
    path('komax_tasks/', views.KomaxTaskListView.as_view(), name='komax_task_list'),
    path('komax_terminals/', views.KomaxTerminalsListView.as_view(), name='komax_terminals_list'),
    path('komax_seals/', views.KomaxSealsListView.as_view(), name='komax_seals_list')
]

komax_site/komax_app/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
#from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
import os
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from django.urls import reverse
from django.http import Http404
import traceback


User = get_user_model()


"""
@receiver(post_save, sender=User)
def create_user_worker(sender, instance, created, **kwargs):
    if created:
        Worker.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_worker(sender, instance, **kwargs):
    instance.worker.save()
"""
class Harness(models.Model):
    created = models.DateField(verbose_name=_('created'), auto_now_add=True)
    harness_number = models.CharField(max_length=64, unique=True, verbose_name=_('harness number'))

    def __str__(self):
        return self.harness_number

class HarnessChart(models.Model):
    harness = models.ForeignKey(Harness, on_delete=models.CASCADE)
    notes = models.CharField(max_length=256, null=True)
    marking = models.CharField(max_length=8)
    wire_type = models.CharField(max_length=128)
    wire_number = models.CharField(max_length=16)
    wire_square = models.FloatField()
    wire_color = models.CharField(max_length=8)
    wire_length = models.PositiveSmallIntegerField()

    armirovka_1 = models.CharField(max_length=128, null=True)
    tube_len_1 = models.CharField(max_length=256, null=True)
    wire_seal_1 = models.CharField(max_length=32, null=True)
    wire_cut_length_1 = models.FloatField()
    wire_terminal_1 = models.CharField(max_length=32, null=True)
    aplicator_1 = models.CharField(max_length=64, null=True)

    armirovka_2 = models.CharField(max_length=128, null=True)
    tube_len_2 = models.CharField(max_length=256, null=True)
    wire_seal_2 = models.CharField(max_length=32, null=True)
    wire_cut_length_2 = models.FloatField()
    wire_terminal_2 = models.CharField(max_length=32, null=True)
    aplicator_2 = models.CharField(max_length=64, null=True)



    def __str__(self):
        return self.harness.harness_number

    @classmethod
    def save_from_dataframe(self, harness_dataframe, harness_number):
        old_harness_charts = self.objects.filter(harness__harness_number__iexact=harness_number)
        if len(old_harness_charts):
            old_harness_charts.delete()

        new_harness_charts = list()
        harness = get_object_or_404(Harness, harness_number=harness_number)
        for row in harness_dataframe.iterrows():
            row_dict = row[1]
            try:
                new_harness_charts.append(
                    self(
                        harness=harness,
                        notes=row_dict["Примечание"],
                        marking=str(row_dict["Маркировка"]),
                        wire_type=str(row_dict["Вид провода"]),
                        wire_number=str(row_dict["№ провода"]),
                        wire_square=float(row_dict["Сечение"]),
                        wire_color=str(row_dict["Цвет"]),
                        wire_length=int(row_dict["Длина, мм (± 3мм)"]),
                        wire_seal_1=str(row_dict["Уплотнитель 1"]),
                        wire_cut_length_1=float(row_dict["Частичное снятие 1"]),
                        wire_terminal_1=str(row_dict["Наконечник 1"]),
                        aplicator_1=str(row_dict["Аппликатор 1"]),
                        tube_len_1=str(row_dict["Длина трубки, L (мм) 1"]),
                        armirovka_1=str(row_dict["Армировка 1 (Трубка ПВХ, Тр. Терм., изоляторы)"]),
                        wire_seal_2=str(row_dict["Уплотнитель 2"]),
                        wire_cut_length_2=float(row_dict["Частичное снятие 2"]),
                        wire_terminal_2=str(row_dict["Наконечник 2"]),
                        aplicator_2=str(row_dict["Аппликатор 2"]),
                        tube_len_2=str(row_dict["Длина трубки, L (мм) 2"]),
                        armirovka_2=str(row_dict["Армировка 2 (Трубка ПВХ, Тр. Терм., изоляторы)"])
                    )
                )
            except Exception as e:
                harness.delete()
                raise Http404(str(e))

        self.objects.bulk_create(new_harness_charts)

class Temp_chart(models.Model):
    harness = models.CharField(max_length=128)
    xlsx = models.FileField(upload_to='temp_charts/')

    def __str__(self):
        return self.harness

class KomaxTerminal(models.Model):
    terminal_name = models.CharField(max_length=64, unique=True)
    terminal_available = models.BooleanField(default=True)
    seal_installed = models.BooleanField(default=True)

    def __str__(self):
        return self.terminal_name + str(self.terminal_available) + str(self.seal_installed)

class KomaxSeal(models.Model):
    seal_name = models.CharField(max_length=64, unique=True)
    seal_available = models.BooleanField(default=True)

    def __str__(self):
        return self.seal_name + str(self.seal_available)

class Kappa(models.Model):
    STATUS_CHOICES = [
        (1, 'Work'),
        (2, 'Repair'),
        (0, 'Not working')
    ]

    number = models.PositiveSmallIntegerField(unique=True, verbose_name=_('kappa'))
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=1)


    def __str__(self):
        return str(self.number)

class Komax(models.Model):
    STATUS_CHOICES = [
        (1, 'Work'),
        (2, 'Repair'),
        (0, 'Not working')
    ]
    MARKING_CHOICES = [
        (2, 'White'),
        (1, 'Black'),
        (3, 'Both')
    ]
    PAIRING_CHOICES = [
        (1, 'Yes'),
        (0, 'No')
    ]

    number = models.PositiveSmallIntegerField(unique=True, verbose_name=_('komaxes'))
    identifier = models.CharField(max_length=256, unique=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=1)
    marking = models.PositiveSmallIntegerField(choices=MARKING_CHOICES, default=1)
    pairing = models.PositiveSmallIntegerField(choices=PAIRING_CHOICES, default=0)
    group_of_square = models.CharField(max_length=6)

    def __str__(self):
        return str(self.number)

class Laboriousness(models.Model):
    action = models.CharField(max_length=256, unique=True)
    time = models.FloatField()

    def __str__(self):
        return self.action
    def get_absolute_url(self):
        return reverse('komax_app:laboriousness')

class HarnessAmount(models.Model):
    harness = models.ForeignKey(Harness, on_delete=models.CASCADE)
    amount = models.SmallIntegerField()

    def __str__(self):
        return self.harness.harness_number

class KomaxTime(models.Model):
    komax = models.ForeignKey(Komax, on_delete=models.CASCADE)
    time = models.IntegerField()

    def __str__(self):
        return  str(self.komax.number) + ' : ' + str(self.time)

class Worker(models.Model):
    LOCALE_CHOICES = [
        (1, 'ru'),
        (2, 'en')
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, db_index=True)
    image = models.ImageField(
        upload_to='worker_images/',
        null=True,
        blank=True,
        editable=True,
    )
    current_komax = models.ForeignKey(Komax, on_delete=models.SET_NULL, blank=True, null=True)
    locale = models.SmallIntegerField('language', choices=LOCALE_CHOICES, default=1)


    def save(self, *args, **kwargs):
        workers = Worker.objects.filter(id=self.id)
        old_path = None
        if len(workers):
            image = workers.first().image
            # image = Worker.objects.get(id=self.id).image

            if bool(image):
                old_path = image.url
                print(os.path.exists(old_path))
                if os.path.exists(old_path):
                    os.remove(image.url)

        if bool(self.image):
            image = Image.open(self.image)
            image_format = self.image.name.split('.')[-1]
            image_name = self.image.name.split('.')[0]

            output = BytesIO()

            image = image.resize((200, 200))
            if image_format == 'png':
                image.save(output, format='PNG', quality=100)
            else:
                image.save(output, format='JPEG', quality=100)
            output.seek(0)

            self.image = InMemoryUploadedFile(output, 'ImageField', '{name}.{format}'.format(name=image_name, format=image_format), 'image/jpeg', sys.getsizeof(output), None)

            if old_path is not None and os.path.exists(old_path):
                os.remove(old_path)
        super(Worker, self).save(*args, **kwargs)


    def __str__(self):
        return "{} - {}".format(self.user, self.current_komax)

class KomaxTask(models.Model):
    LOADING_TYPES = [
        ('New', 'New'),
        ('Mix', 'Mix'),
        ('Urgent', 'Urgent')
    ]

    ALLOCATION_TYPES = [
        ('Parallel', 'Parallel'),
        ('Consistently', 'Consistently'),
    ]

    STATUS_TYPES = [
        (1, 'Created'),
        (2, 'Ordered'),
        (3, 'Loaded'),
        (4, 'Done')
    ]

    task_name = models.CharField(max_length=128, unique=True)
    created = models.DateTimeField(verbose_name=_('created'), auto_now_add=True)
    harnesses = models.ManyToManyField(HarnessAmount)
    komaxes = models.ManyToManyField(KomaxTime)
    kappas = models.ForeignKey(Kappa, on_delete=models.CASCADE, null=True)
    shift = models.PositiveSmallIntegerField()
    type_of_allocation = models.CharField(default='Parallel', max_length=128, choices=ALLOCATION_TYPES)
    loading_type = models.CharField(default='New', max_length=64, choices=LOADING_TYPES)
    status = models.SmallIntegerField(choices=STATUS_TYPES, default=1)
    # worker = models.ForeignKey(Worker,on_delete=models.CASCADE, null=True)
    # ordered = models.BooleanField(default=False)

komax_site/komax_app/templates/komax_app/harnesses.html
{% extends 'komax_app/dashboard_main.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% trans 'Harnesses' %}</title>
{% endblock %}

{% block main %}

    <link type="text/css" rel="stylesheet" href="{% static 'komax_app/harnesses.css' %}">

    <div class="container">
    <h2 class="text-center">{% trans 'Wire charts' %}</h2>

    <div class="harness-upload-form">
        {% if perms.komax_app.add_harness %}
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-xs-12 col-sm-6" id="harness_number_handler">
                            <input class="harness-number form-control" id='harness_number' name="harness_number" type="text" required placeholder="5490-3724144-05">
                        </div>
                        <div class="col-xs-12 col-sm-4">
                            <div class="harness-upload-custom">
                                <div class="form-group">
                                    <input class="input-file" id="harness_chart" name="harness_chart" type="file" required>
                                    <label class="btn btn-tertiary js-labelFile" for="harness_chart">
                                        <i class="icon fa fa-check"> {% trans "Chart" %}</i>
                                        <span class="js-fileName"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-push-4 col-xs-pull-4 col-xs-4 col-sm-2">
                            <button type="submit" class="harness-btn btn btn-success">{% trans 'Upload' %}</button>
                        </div>
                    </div>
                </div>

            </form>
        {% endif %}
    </div>

    </div>

    <div class="container">
        <div class="harnesses-items-table">
            <table class="table table-stripped">
            <thred>
                <tr>
                    <div class="row">
                        <th class="text-center" scope="col">{% trans 'Harness number' %}</th>
                        <th class="text-center" scope="col">{% trans 'Date' %}</th>
                        {% if perms.komax_app.view_harness %}
                        <th scope="col"></th>
                        {% endif %}
                        {% if perms.komax_app.view_harness %}
                        <th scope="col"></th>
                        {% endif %}
                        {% if perms.komax_app.delete_harness %}
                        <th scope="col"></th>
                        {% endif %}
                    </div>
                </tr>
            </thred>
            <tbody>

            {% for pos in harnesses %}
            <div class="row">
                <tr>
                    <td class="text-center">{{ pos.harness_number }}</td>
                    <td class="text-center">{{ pos.created }}</td>
                    {% if perms.komax_app.view_harness %}
                    <td>
                        <a href="{% url 'komax_app:harness_chart' harness_number=pos.harness_number %}">
                            <button title="{% trans 'Detailed' %}" class="btn btn-secondary show-btn" >
                                <i class="fa fa-search"> </i>
                            </button>
                        </a>
                    </td>
                    {% endif %}
                    {% if perms.komax_app.view_harness %}
                    <td>
                        <a href="{% url 'komax_app:download_harness' harness_number=pos.harness_number %}">
                            <button title="{% trans 'Download' %}" class="btn btn-info">
                                <i class="fa fa-download"> </i>
                            </button>
                        </a>
                    </td>
                    {% endif %}
                    {% if perms.komax_app.delete_harness %}
                    <td>
                        <a href="{% url 'komax_app:delete_harness' harness_number=pos.harness_number %}">
                            <button title="{% trans 'Delete' %}" class="btn btn-danger delete-btn">
                                <i class="fa fa-trash"> </i>
                            </button>
                        </a>
                    </td>
                    {% endif %}
                </tr>
            </div>
            {% endfor %}
            </tbody>
            </table>
        </div>
    </div>

<script>


  $('.input-file').each(function() {
    var $input = $(this),
        $label = $input.next('.js-labelFile'),
        labelVal = $label.html();

   $input.on('change', function(element) {
      var fileName = '';
      if (element.target.value) fileName = element.target.value.split('\\').pop();
      console.log(fileName);
      fileName ? $label.addClass('has-file').find('.js-fileName').html(fileName) : $label.removeClass('has-file').html(labelVal);
   });
  });

</script>

<script>
    var loc = window.location;
    var wsStart = 'wss://';
    if (loc.host.includes('localhost')){
        wsStart = 'ws://'
    }
    var endPoint = wsStart + loc.host + loc.pathname;
    var socket = new WebSocket(endPoint);

    var input_harness_number = $('#harness_number');

    socket.onopen = function(e) {
        input_harness_number.change(function(event){
           event.preventDefault();
           var harness_number = input_harness_number.val();

           if (harness_number.length > 0){
               socket.send(JSON.stringify({
                   'harness_number': harness_number
               }));
           }
           else {
               input_harness_number.removeClass('is-valid');
               input_harness_number.removeClass('is-invalid');
               $('.invalid-feedback').remove()
           }

        });
    };
    socket.onmessage = function(e) {
        msg = JSON.parse(e.data);

        if (msg.checker == 0){
            input_harness_number.removeClass('is-valid');
            input_harness_number.addClass("is-invalid");
            var harness_number_handler = $('#harness_number_handler');
            harness_number_handler.append(
                '<div class="invalid-feedback">' +
                'A - Z, a - z, 0 - 9, А - Я, а - я, -' +
                '</div>'
            )
        }
        else {
            input_harness_number.removeClass("is-invalid");
            input_harness_number.addClass("is-valid");
            var feedback_invalid = $('.invalid-feedback');
            feedback_invalid.remove();
        }
    };
    socket.onerror = function(e) {

    };
    socket.onclose = function(e) {

    }





</script>
{% endblock %}

komax_site/komax_app/templates/komax_app/komax_app_main.html
{% extends 'main.html' %}
{% load static %}
{% load i18n %}

{% block navbar %}
    <link type="text/css" rel="stylesheet" href="{% static 'komax_app/komax_app_main.css' %}">
    <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% trans 'App' %}
            <span class="sr-only">({% trans 'current' %})</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'komax_app:komax_app_view' %}">{% trans 'App' %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:harnesses' %}">{% trans 'Harnesses' %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:komaxes' %}">{% trans 'Komaxes' %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:laboriousness' %}">{% trans 'Laboriousness' %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:komax_task_list' %}">{% trans "Komax tasks" %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:komax_terminals_list' %}">{% trans 'Komax terminals' %}</a>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'description:description' %}">{% trans 'About' %}</a>
    </li>
    <li>

        <div class="language_button">

        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}" >
            <select name="language">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
            </select>
            <input type="submit" value="Go" />
        </form>
        </div>

    </li>


{% endblock %}

komax_site/komax_app/templates/komax_app/komax_app_task.html
{% extends 'komax_app/komax_app_main.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    <title>{% trans 'Task' %} {{ task.task_name }}</title>
{% endblock %}

{% block libraries %}

{% endblock %}

{% block main_content %}
    <link rel="stylesheet" type="text/css" href="{% static 'komax_app/komax_app_task.css' %}">
    <section class="jumbotron text-center">
        <div class="container-fluid">
            <h1 class="jumbotron-heading">Komax {% trans 'task' %} {{ task.task_name }}</h1>
            <h5>{% trans 'Succesfully allocated!' %}</h5>
            <p>
                <a class="btn btn-primary btn-lg" href="{% url 'komax_app:get_task' task_name=task.task_name %}">
                    {% trans 'Full' %} {% trans 'task' %}
                </a>

                {% for komax, time in alloc.items %}
                    <a class="btn btn-primary btn-lg" href="{% url 'komax_app:get_spec_task' task_name=task.task_name komax=komax %}">
                        {% trans 'task' %} {{ komax }}
                    </a>
                {% endfor %}
                {% for kappa in kappas %}
                    <a class="btn btn-primary btn-lg" href="{% url 'komax_app:get_spec_task_kappa' task_name=task.task_name kappa=kappa.number %}">
                        {% trans 'task' %} kappa {{ kappa.number }}
                    </a>
                {% endfor %}
            </p>
            <p>
                <a class="btn btn-lg btn-warning" href="{% url 'komax_app:task_setup' %}">{% trans 'Again' %}</a>
            </p>
            <p>
                <a class="btn btn-lg btn-success" href="{% url 'komax_app:send_komax_task' task_name=task.task_name %}">
                    {% trans 'Load task' %}
                </a>
                <!--
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg btn-success">
                        {% trans 'Load task' %}
                    </button>
                </form>
                -->

            </p>
        </div>
    </section>

    <div class="container-fluid text-center">

        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">{% trans 'Tickets' %}</h3>
                        <p class="card-text">
                            {% for komax, time in alloc.items %}
                                <a class="btn btn-lg btn-info" href="{% url 'komax_app:get_ticket_view' task_name=task.task_name komax=komax %}">
                                    {% trans "Ticket" %} {{ komax }}
                                </a>

                            {% endfor %}
                            {% for kappa in kappas %}
                                <a class="btn btn-lg btn-info" href="{% url 'komax_app:get_kappa_ticket_view' task_name=task.task_name kappa=kappa.number %}">
                                    {% trans 'Ticket' %} kappa {{ kappa.number }}
                                </a>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">{% trans 'Harnesses' %} {% trans 'used' %}</h3>

                            {% for harness in harnesses %}
                                <p class="card-text">
                                <h4>{{ harness }}</h4>
                                <p>{{ harness.amount }}</p>
                                </p>
                            {% endfor %}

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="card">
                    <p class="card-body">
                        <h3 class="card-title">Komaxes {% trans 'used' %}</h3>

                        <p class="card-text">
                        {% if exceeds_shift %}
                            <p>
                                <h4>
                                <i class="fa fa-exclamation-triangle btn-danger"> </i>
                                    {% blocktrans %}
                                        Exceeds shift. Please load next shift!
                                    {% endblocktrans %}
                                <i class="fa fa-exclamation-triangle btn-danger"> </i>
                                </h4>
                            </p>
                        {% endif %}
                        {% for komax, time in alloc.items %}
                            <p>
                                <h3>{{ komax }} - {{ time }}</h3>
                            </p>
                        {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

komax_site/komax_app/templates/komax_app/laboriousness_create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <form method="POST">
            {% csrf_token %}
                {{ form }}
                <button class="btn btn-outline-info" type="submit">Submit</button>
        </form>
</body>
</html>