komax_site/api/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.routers import DefaultRouter
from .viewsets import KomaxViewSet, KappaViewSet, HarnessViewSet, LabourisnessViewSet, KomaxTerminalsViewSet, \
    KomaxStatusViewSet, HarnessChartViewSet, KomaxSealViewSet, WorkerViewSet, KomaxTaskViewSet

app_name = 'api'

router = DefaultRouter()
router.register('komaxes', KomaxViewSet)
router.register('kappas', KappaViewSet)
router.register('harnesses', HarnessViewSet)
router.register('laboriousness', LabourisnessViewSet)
router.register('komax_terminals', KomaxTerminalsViewSet)
router.register('komax_status', KomaxStatusViewSet)
router.register('harness_chart', HarnessChartViewSet)
router.register('komax_seals', KomaxSealViewSet)
router.register('workers', WorkerViewSet)
router.register('komax_tasks', KomaxTaskViewSet, basename='komax-tasks')


urlpatterns = [
    path('index/', views.index, name='index'),
    path('v1/login/', ObtainAuthToken.as_view(), name='get_token'),
    path('v1/logout/', views.Logout.as_view(), name='logout'),
    path('v1/<str:task_name>/stop', views.KomaxTaskStop.as_view(), name='stop_task'),
    path('v1/<str:task_name>/stop/<str:komax>/', views.KomaxTaskStopOnKomax.as_view(), name='stop_task_on_komax'),
    path('v1/load_komax_task/', views.LoadTaskView.as_view(), name='load-komax-task'),
    path('v1/send_komax_task/', views.SendTaskView.as_view(), name='send-komax-task'),
    path('v1/worker_account/', views.WorkerAccountView.as_view(), name='worker-account'),
    path('v1/komax_task_status/', views.TaskStatusView.as_view(), name='komax-task-status'),
    path('v1/groups/', views.UserGroupView.as_view(), name='user-groups'),
    path('v1/<str:task_name>/get_task/', views.get_general_task_view, name='get_task'),
    path('v1/<str:task_name>/get_task_komax/<str:komax>/',
         views.get_personal_task_view_komax, name='get_spec_task'),
    path('v1/<str:task_name>/get_task_kappa/<str:kappa>/',
         views.get_personal_task_view_kappa, name='get_spec_task_kappa'),
    path('v1/<str:task_name>/get_ticket_komax/<str:komax>/',
         views.get_komax_ticket_view, name='get_ticket_view'),
    path('v1/<str:task_name>/get_ticket_kappa/<str:kappa>/',
         views.get_kappa_ticket_view, name='get_kappa_ticket_view'),
    # path('v1/xlsx_task/', views.XlsxTaskView.as_view(), name='xlsx-task'),
    path('v1/', include(router.urls)),
]

komax_site/description/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

app_name = 'description'
urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='description/description.html'), name='description'),
]

komax_site/komax_app/urls.py
from django.urls import path
from . import views

app_name = 'komax_app'

urlpatterns = [
    # main
    path('', views.MainPageKomaxAppView.as_view(), name='komax_app_view'),

    # komax api
    path('api/v1/komax/', views.KomaxClientView.as_view(), name='komax_client'),

    # tasks
    path('tasks/', views.TasksView.as_view(), name='tasks_view'),
    path('account/', views.WorkerAccountView.as_view(), name='user_account'),
    path('tasks/setup/', views.KomaxTaskSetupView.as_view(), name='task_setup'),
    path('tasks/<str:task_name>/', views.KomaxTaskView.as_view(), name='task_view'),
    path('tasks/<str:task_name>/delete/', views.delete_task, name='delete_task'),
    path('tasks/<str:task_name>/stop', views.stop_komax_task, name='stop_task'),
    path('tasks/<str:task_name>/stop/<str:komax>/', views.stop_task_on_komax, name='stop_task_on_komax'),
    path('tasks/<str:task_name>/get_task/', views.get_general_task_view, name='get_task'),
    path('tasks/<str:task_name>/get_task_komax/<str:komax>/',
            views.get_personal_task_view_komax, name='get_spec_task'),
    path('tasks/<str:task_name>/get_task_kappa/<str:kappa>/',
            views.get_personal_task_view_kappa, name='get_spec_task_kappa'),
    path('tasks/<str:task_name>/get_ticket_komax/<str:komax>/',
            views.get_komax_ticket_view, name='get_ticket_view'),
    path('tasks/<str:task_name>/get_ticket_kappa/<str:kappa>/',
         views.get_kappa_ticket_view, name='get_kappa_ticket_view'),
    path('tasks/<str:task_name>/send_task/', views.send_task_to_worker,
                name='send_komax_task'),
    path('tasks/<task_name>/load_task/', views.load_task_to_komax, name='load_komax_task'),

    # harnesses
    path('harnesses/', views.HarnessesListView.as_view(), name='harnesses'),
    path('harnesses/<str:harness_number>', views.harness_chart_view, name='harness_chart'),
    path('harnesses/<str:harness_number>/delete/', views.harness_delete, name='delete_harness'),
    path('harnesses/<str:harness_number>/download/', views.get_harness_chart_view, name='download_harness'),

    # komaxes
    path('komaxes/', views.EquipmentListView.as_view(), name='komaxes'),

    # laboriousness
    path('laboriousness/edit/<str:action>/delete/', views.LaboriousnessDeleteView.as_view(), name='laboriousness-delete'),
    path('laboriousness/create/', views.LaboriousnessCreateView.as_view(), name='laboriousness-create'),
    path('laboriousness/edit/<str:action>', views.LaboriousnessEditView.as_view(), name='laboriousness-edit'),
    path('laboriousness/', views.LaboriousnessListView.as_view(), name='laboriousness'),

    # others
    path('komax_tasks/', views.KomaxTaskListView.as_view(), name='komax_task_list'),
    path('komax_terminals/', views.KomaxTerminalsListView.as_view(), name='komax_terminals_list'),
    path('komax_seals/', views.KomaxSealsListView.as_view(), name='komax_seals_list')
]

komax_site/main_app/urls.py
from django.urls import path, re_path

from django.views.generic import TemplateView

app_name = 'main_app'
urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='main_app/welcome.html'), name='main_app'),
]

komax_site/main_app/models.py
import datetime
from django.db import models
from django.utils import timezone

komax_site/main_app/templates/main_app/main_app_main.html
{% extends 'main.html' %}
{% load staticfiles %}
{% load i18n %}

{% block navbar %}
    <li class="nav-item">
      <!-- Set normal link for Main page -->
        <a class="nav-link active" href="{% url 'main_app:main_app' %}">
            {% trans 'Main' %}
            <span class="sr-only">({% trans 'current' %})</span>
        </a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% trans 'App' %}
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'komax_app:komax_app_view' %}">{% trans 'App' %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:harnesses' %}">{% trans 'Harnesses' %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:komaxes' %}">{% trans 'Komaxes' %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:laboriousness' %}">{% trans 'Laboriousness' %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:komax_task_list' %}">{% trans "Komax tasks" %}</a>
            <a class="dropdown-item" href="{% url 'komax_app:komax_terminals_list' %}">{% trans 'Komax terminals' %}</a>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'description:description' %}">
            {% trans 'About' %}
        </a>
    </li>

{% endblock %}

komax_site/main_app/templates/main_app/welcome.html
{% extends 'main_app/main_app_main.html' %}
{% load i18n %}
{% load staticfiles %}
{% load static %}

{% block tittle %}
<title>PRETTL-NK</title>
{% endblock %}
{% block main_content %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'main_app/welcome.css' %}" >
    <div class="carousel slide" data-ride="carousel" id="slides">
    <ul class="carousel-indicators">
        <li data-target="#slides" data-slide-to="0" class="active"></li>
    </ul>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'main_app/image/background.jpg' %}">
            <div class="carousel-caption">
                <h1 class="display-2">{% trans 'Automation platform'%}</h1>
                <h3>{% trans "Automated tasks create" %}</h3>
                <a class="btn btn-primary btn-lg" type="button" href="{% url 'description:description' %}">
                    {% trans 'About' %}
                </a>
                <a type="button" class="btn btn-warning btn-lg" href="{% url 'komax_app:task_setup' %}">
                    {% trans 'Automate' %}
                </a>
            </div>
        </div>
    </div>
    </div>
{% endblock %}


                <h1 class="display-2">Платформа автоматизации</h1>
                <h3>Автоматизированная выдача наряд-заданий</h3>
                <a class="btn btn-primary btn-lg" type="button" href="{% url 'description:description' %}">О платформе</a>
                <a type="button" class="btn btn-secondary btn-lg" href="{% url 'komax_app:task_setup' %}">
                    Автоматизировать
                </a>